package main

type IconDetails struct {
	Icon       string
	Color      string
	CtermColor string
	Name       string
}

var DefaultIcon = IconDetails{
	Icon:       "",
	Color:      "#383838",
	CtermColor: "24",
	Name:       "Default",
}

var iconsByFileName = map[string]IconDetails{
	"build.gradle": {
		Icon:       "",
		Color:      "#005f87",
		CtermColor: "24",
		Name:       "GradleBuildScript",
	},
	"settings.gradle": {
		Icon:       "",
		Color:      "#005f87",
		CtermColor: "24",
		Name:       "GradleSettings",
	},
	".babelrc": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Babelrc",
	},
	".bash_profile": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "BashProfile",
	},
	".bashrc": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Bashrc",
	},
	".dockerignore": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	".ds_store": {
		Icon:       "",
		Color:      "#41535b",
		CtermColor: "239",
		Name:       "DsStore",
	},
	".editorconfig": {
		Icon:       "",
		Color:      "#fff2f2",
		CtermColor: "255",
		Name:       "EditorConfig",
	},
	".env": {
		Icon:       "",
		Color:      "#faf743",
		CtermColor: "227",
		Name:       "Env",
	},
	".eslintrc": {
		Icon:       "",
		Color:      "#4b32c3",
		CtermColor: "56",
		Name:       "Eslintrc",
	},
	".eslintignore": {
		Icon:       "",
		Color:      "#4b32c3",
		CtermColor: "56",
		Name:       "EslintIgnore",
	},
	".gitattributes": {
		Icon:       "",
		Color:      "#f54d27",
		CtermColor: "196",
		Name:       "GitAttributes",
	},
	".gitconfig": {
		Icon:       "",
		Color:      "#f54d27",
		CtermColor: "196",
		Name:       "GitConfig",
	},
	".gitignore": {
		Icon:       "",
		Color:      "#f54d27",
		CtermColor: "196",
		Name:       "GitIgnore",
	},
	".gitlab-ci.yml": {
		Icon:       "",
		Color:      "#e24329",
		CtermColor: "196",
		Name:       "GitlabCI",
	},
	".gitmodules": {
		Icon:       "",
		Color:      "#f54d27",
		CtermColor: "196",
		Name:       "GitModules",
	},
	".gtkrc-2.0": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "GTK",
	},
	".gvimrc": {
		Icon:       "",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "Gvimrc",
	},
	".justfile": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Justfile",
	},
	".luaurc": {
		Icon:       "",
		Color:      "#00a2ff",
		CtermColor: "75",
		Name:       "Luaurc",
	},
	".mailmap": {
		Icon:       "󰊢",
		Color:      "#41535b",
		CtermColor: "239",
		Name:       "Mailmap",
	},
	".npmignore": {
		Icon:       "",
		Color:      "#E8274B",
		CtermColor: "197",
		Name:       "NPMIgnore",
	},
	".npmrc": {
		Icon:       "",
		Color:      "#E8274B",
		CtermColor: "197",
		Name:       "NPMrc",
	},
	".nvmrc": {
		Icon:       "",
		Color:      "#5FA04E",
		CtermColor: "71",
		Name:       "node",
	},
	".prettierrc": {
		Icon:       "",
		Color:      "#4285F4",
		CtermColor: "33",
		Name:       "PrettierConfig",
	},
	".settings.json": {
		Icon:       "",
		Color:      "#854CC7",
		CtermColor: "98",
		Name:       "SettingsJson",
	},
	".SRCINFO": {
		Icon:       "󰣇",
		Color:      "#0f94d2",
		CtermColor: "67",
		Name:       "SRCINFO",
	},
	".vimrc": {
		Icon:       "",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "Vimrc",
	},
	".Xauthority": {
		Icon:       "",
		Color:      "#e54d18",
		CtermColor: "196",
		Name:       "Xauthority",
	},
	".xinitrc": {
		Icon:       "",
		Color:      "#e54d18",
		CtermColor: "196",
		Name:       "XInitrc",
	},
	".Xresources": {
		Icon:       "",
		Color:      "#e54d18",
		CtermColor: "196",
		Name:       "Xresources",
	},
	".xsession": {
		Icon:       "",
		Color:      "#e54d18",
		CtermColor: "196",
		Name:       "Xsession",
	},
	".zprofile": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Zshprofile",
	},
	".zshenv": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Zshenv",
	},
	".zshrc": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Zshrc",
	},
	"_gvimrc": {
		Icon:       "",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "Gvimrc",
	},
	"_vimrc": {
		Icon:       "",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "Vimrc",
	},
	"R": {
		Icon:       "󰟔",
		Color:      "#2266ba",
		CtermColor: "25",
		Name:       "R",
	},
	"avif": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Avif",
	},
	"brewfile": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "Brewfile",
	},
	"bspwmrc": {
		Icon:       "",
		Color:      "#2f2f2f",
		CtermColor: "236",
		Name:       "BSPWM",
	},
	"build": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "BazelBuild",
	},
	"checkhealth": {
		Icon:       "󰓙",
		Color:      "#75B4FB",
		CtermColor: "75",
		Name:       "Checkhealth",
	},
	"cmakelists.txt": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "CMakeLists",
	},
	"commit_editmsg": {
		Icon:       "",
		Color:      "#f54d27",
		CtermColor: "196",
		Name:       "GitCommit",
	},
	"compose.yaml": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	"compose.yml": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	"config": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Config",
	},
	"containerfile": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	"copying": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "License",
	},
	"copying.lesser": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "License",
	},
	"docker-compose.yaml": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	"docker-compose.yml": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	"dockerfile": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	"ext_typoscript_setup.txt": {
		Icon:       "",
		Color:      "#FF8700",
		CtermColor: "208",
		Name:       "TypoScriptSetup",
	},
	"favicon.ico": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Favicon",
	},
	"fp-info-cache": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCadCache",
	},
	"fp-lib-table": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCadFootprintTable",
	},
	"FreeCAD.conf": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCADConfig",
	},
	"gemfile$": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "Gemfile",
	},
	"gnumakefile": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Makefile",
	},
	"gradlew": {
		Icon:       "",
		Color:      "#005f87",
		CtermColor: "24",
		Name:       "GradleWrapperScript",
	},
	"gradle.properties": {
		Icon:       "",
		Color:      "#005f87",
		CtermColor: "24",
		Name:       "GradleProperties",
	},
	"gradle-wrapper.properties": {
		Icon:       "",
		Color:      "#005f87",
		CtermColor: "24",
		Name:       "GradleWrapperProperties",
	},
	"groovy": {
		Icon:       "",
		Color:      "#4a687c",
		CtermColor: "24",
		Name:       "Groovy",
	},
	"gruntfile.babel.js": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Gruntfile",
	},
	"gruntfile.coffee": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Gruntfile",
	},
	"gruntfile.js": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Gruntfile",
	},
	"gruntfile.ts": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Gruntfile",
	},
	"gtkrc": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "GTK",
	},
	"gulpfile.babel.js": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "Gulpfile",
	},
	"gulpfile.coffee": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "Gulpfile",
	},
	"gulpfile.js": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "Gulpfile",
	},
	"gulpfile.ts": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "Gulpfile",
	},
	"hyprland.conf": {
		Icon:       "",
		Color:      "#00aaae",
		CtermColor: "37",
		Name:       "Hyprland",
	},
	"i3blocks.conf": {
		Icon:       "",
		Color:      "#e8ebee",
		CtermColor: "255",
		Name:       "i3",
	},
	"i3status.conf": {
		Icon:       "",
		Color:      "#e8ebee",
		CtermColor: "255",
		Name:       "i3",
	},
	"cantorrc": {
		Icon:       "",
		Color:      "#1c99f3",
		CtermColor: "32",
		Name:       "Cantorrc",
	},
	"justfile": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Justfile",
	},
	"kalgebrarc": {
		Icon:       "",
		Color:      "#1c99f3",
		CtermColor: "32",
		Name:       "Kalgebrarc",
	},
	"kdeglobals": {
		Icon:       "",
		Color:      "#1c99f3",
		CtermColor: "32",
		Name:       "KDEglobals",
	},
	"kdenlive-layoutsrc": {
		Icon:       "",
		Color:      "#83b8f2",
		CtermColor: "110",
		Name:       "KdenliveLayoutsrc",
	},
	"kdenliverc": {
		Icon:       "",
		Color:      "#83b8f2",
		CtermColor: "110",
		Name:       "Kdenliverc",
	},
	"kritadisplayrc": {
		Icon:       "",
		Color:      "#f245fb",
		CtermColor: "201",
		Name:       "Kritadisplayrc",
	},
	"kritarc": {
		Icon:       "",
		Color:      "#f245fb",
		CtermColor: "201",
		Name:       "Kritarc",
	},
	"license": {
		Icon:       "",
		Color:      "#d0bf41",
		CtermColor: "185",
		Name:       "License",
	},
	"lxde-rc.xml": {
		Icon:       "",
		Color:      "#909090",
		CtermColor: "246",
		Name:       "LXDEConfigFile",
	},
	"lxqt.conf": {
		Icon:       "",
		Color:      "#0192d3",
		CtermColor: "32",
		Name:       "LXQtConfigFile",
	},
	"makefile": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Makefile",
	},
	"mix.lock": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "MixLock",
	},
	"mpv.conf": {
		Icon:       "",
		Color:      "#3b1342",
		CtermColor: "53",
		Name:       "Mpv",
	},
	"node_modules": {
		Icon:       "",
		Color:      "#E8274B",
		CtermColor: "197",
		Name:       "NodeModules",
	},
	"package.json": {
		Icon:       "",
		Color:      "#e8274b",
		CtermColor: "197",
		Name:       "PackageJson",
	},
	"package-lock.json": {
		Icon:       "",
		Color:      "#7a0d21",
		CtermColor: "52",
		Name:       "PackageLockJson",
	},
	"PKGBUILD": {
		Icon:       "",
		Color:      "#0f94d2",
		CtermColor: "67",
		Name:       "PKGBUILD",
	},
	"platformio.ini": {
		Icon:       "",
		Color:      "#f6822b",
		CtermColor: "208",
		Name:       "Platformio",
	},
	"pom.xml": {
		Icon:       "",
		Color:      "#7a0d21",
		CtermColor: "52",
		Name:       "Maven",
	},
	"procfile": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Procfile",
	},
	"PrusaSlicer.ini": {
		Icon:       "",
		Color:      "#ec6b23",
		CtermColor: "202",
		Name:       "PrusaSlicer",
	},
	"PrusaSlicerGcodeViewer.ini": {
		Icon:       "",
		Color:      "#ec6b23",
		CtermColor: "202",
		Name:       "PrusaSlicer",
	},
	"py.typed": {
		Icon:       "",
		Color:      "#ffbc03",
		CtermColor: "214",
		Name:       "Py.typed",
	},
	"QtProject.conf": {
		Icon:       "",
		Color:      "#40cd52",
		CtermColor: "77",
		Name:       "Qt",
	},
	"r": {
		Icon:       "󰟔",
		Color:      "#2266ba",
		CtermColor: "25",
		Name:       "R",
	},
	"rakefile": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "Rakefile",
	},
	"rmd": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Rmd",
	},
	"svelte.config.js": {
		Icon:       "",
		Color:      "#ff3e00",
		CtermColor: "196",
		Name:       "SvelteConfig",
	},
	"sxhkdrc": {
		Icon:       "",
		Color:      "#2f2f2f",
		CtermColor: "236",
		Name:       "BSPWM",
	},
	"sym-lib-table": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCadSymbolTable",
	},
	"tailwind.config.js": {
		Icon:       "󱏿",
		Color:      "#20c2e3",
		CtermColor: "45",
		Name:       "TailwindConfig",
	},
	"tailwind.config.mjs": {
		Icon:       "󱏿",
		Color:      "#20c2e3",
		CtermColor: "45",
		Name:       "TailwindConfig",
	},
	"tailwind.config.ts": {
		Icon:       "󱏿",
		Color:      "#20c2e3",
		CtermColor: "45",
		Name:       "TailwindConfig",
	},
	"tmux.conf": {
		Icon:       "",
		Color:      "#14ba19",
		CtermColor: "34",
		Name:       "Tmux",
	},
	"tmux.conf.local": {
		Icon:       "",
		Color:      "#14ba19",
		CtermColor: "34",
		Name:       "Tmux",
	},
	"tsconfig.json": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "TSConfig",
	},
	"unlicense": {
		Icon:       "",
		Color:      "#d0bf41",
		CtermColor: "185",
		Name:       "License",
	},
	"vagrantfile$": {
		Icon:       "",
		Color:      "#1563FF",
		CtermColor: "27",
		Name:       "Vagrantfile",
	},
	"vlcrc": {
		Icon:       "󰕼",
		Color:      "#ee7a00",
		CtermColor: "208",
		Name:       "VLC",
	},
	"webpack": {
		Icon:       "󰜫",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Webpack",
	},
	"weston.ini": {
		Icon:       "",
		Color:      "#ffbb01",
		CtermColor: "214",
		Name:       "Weston",
	},
	"workspace": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "BazelWorkspace",
	},
	"xmobarrc": {
		Icon:       "",
		Color:      "#fd4d5d",
		CtermColor: "203",
		Name:       "xmonad",
	},
	"xmobarrc.hs": {
		Icon:       "",
		Color:      "#fd4d5d",
		CtermColor: "203",
		Name:       "xmonad",
	},
	"xmonad.hs": {
		Icon:       "",
		Color:      "#fd4d5d",
		CtermColor: "203",
		Name:       "xmonad",
	},
	"xorg.conf": {
		Icon:       "",
		Color:      "#e54d18",
		CtermColor: "196",
		Name:       "XorgConf",
	},
	"xsettingsd.conf": {
		Icon:       "",
		Color:      "#e54d18",
		CtermColor: "196",
		Name:       "XSettingsdConf",
	},
	"build.zig.zon": {
		Icon:       "",
		Color:      "#f69a1b",
		CtermColor: "172",
		Name:       "ZigObjectNotation",
	},
}

var iconsByFileExtension = map[string]IconDetails{
	"3gp": {
		Icon:       "",
		Color:      "#FD971F",
		CtermColor: "208",
		Name:       "3gp",
	},
	"3mf": {
		Icon:       "󰆧",
		Color:      "#888888",
		CtermColor: "102",
		Name:       "3DObjectFile",
	},
	"7z": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "7z",
	},
	"a": {
		Icon:       "",
		Color:      "#dcddd6",
		CtermColor: "253",
		Name:       "StaticLibraryArchive",
	},
	"aac": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "AdvancedAudioCoding",
	},
	"aif": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "AudioInterchangeFileFormat",
	},
	"aiff": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "AudioInterchangeFileFormat",
	},
	"ape": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "MonkeysAudio",
	},
	"ai": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Ai",
	},
	"android": {
		Icon:       "",
		Color:      "#34a853",
		CtermColor: "35",
		Name:       "Android",
	},
	"apk": {
		Icon:       "",
		Color:      "#34a853",
		CtermColor: "35",
		Name:       "apk",
	},
	"app": {
		Icon:       "",
		Color:      "#9F0500",
		CtermColor: "124",
		Name:       "App",
	},
	"applescript": {
		Icon:       "",
		Color:      "#6d8085",
		CtermColor: "66",
		Name:       "AppleScript",
	},
	"asc": {
		Icon:       "󰦝",
		Color:      "#576d7f",
		CtermColor: "242",
		Name:       "Asc",
	},
	"ass": {
		Icon:       "󰨖",
		Color:      "#ffb713",
		CtermColor: "214",
		Name:       "Ass",
	},
	"astro": {
		Icon:       "",
		Color:      "#e23f67",
		CtermColor: "197",
		Name:       "Astro",
	},
	"awk": {
		Icon:       "",
		Color:      "#4d5a5e",
		CtermColor: "240",
		Name:       "Awk",
	},
	"azcli": {
		Icon:       "",
		Color:      "#0078d4",
		CtermColor: "32",
		Name:       "AzureCli",
	},
	"bak": {
		Icon:       "󰁯",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Backup",
	},
	"bash": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Bash",
	},
	"bat": {
		Icon:       "",
		Color:      "#C1F12E",
		CtermColor: "191",
		Name:       "Bat",
	},
	"bazel": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Bazel",
	},
	"bib": {
		Icon:       "󱉟",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "BibTeX",
	},
	"bicep": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Bicep",
	},
	"bicepparam": {
		Icon:       "",
		Color:      "#9f74b3",
		CtermColor: "133",
		Name:       "BicepParameters",
	},
	"bin": {
		Icon:       "",
		Color:      "#9F0500",
		CtermColor: "124",
		Name:       "Bin",
	},
	"blade.php": {
		Icon:       "",
		Color:      "#f05340",
		CtermColor: "203",
		Name:       "Blade",
	},
	"blend": {
		Icon:       "󰂫",
		Color:      "#ea7600",
		CtermColor: "208",
		Name:       "Blender",
	},
	"bmp": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Bmp",
	},
	"blp": {
		Icon:       "󰺾",
		Color:      "#5796E2",
		CtermColor: "68",
		Name:       "Blueprint",
	},
	"brep": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "BoundaryRepresentation",
	},
	"bz": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Bz",
	},
	"bz2": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Bz2",
	},
	"bz3": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Bz3",
	},
	"bzl": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Bzl",
	},
	"c": {
		Icon:       "",
		Color:      "#599eff",
		CtermColor: "111",
		Name:       "C",
	},
	"c++": {
		Icon:       "",
		Color:      "#f34b7d",
		CtermColor: "204",
		Name:       "CPlusPlus",
	},
	"cache": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "Cache",
	},
	"cast": {
		Icon:       "",
		Color:      "#FD971F",
		CtermColor: "208",
		Name:       "Asciinema",
	},
	"cbl": {
		Icon:       "⚙",
		Color:      "#005ca5",
		CtermColor: "25",
		Name:       "Cobol",
	},
	"cc": {
		Icon:       "",
		Color:      "#f34b7d",
		CtermColor: "204",
		Name:       "CPlusPlus",
	},
	"ccm": {
		Icon:       "",
		Color:      "#f34b7d",
		CtermColor: "204",
		Name:       "CPlusPlusModule",
	},
	"cfg": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Configuration",
	},
	"cjs": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Cjs",
	},
	"clj": {
		Icon:       "",
		Color:      "#8dc149",
		CtermColor: "113",
		Name:       "Clojure",
	},
	"cljc": {
		Icon:       "",
		Color:      "#8dc149",
		CtermColor: "113",
		Name:       "ClojureC",
	},
	"cljs": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "ClojureJS",
	},
	"cljd": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "ClojureDart",
	},
	"cmake": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "CMake",
	},
	"cob": {
		Icon:       "⚙",
		Color:      "#005ca5",
		CtermColor: "25",
		Name:       "Cobol",
	},
	"cobol": {
		Icon:       "⚙",
		Color:      "#005ca5",
		CtermColor: "25",
		Name:       "Cobol",
	},
	"coffee": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Coffee",
	},
	"conf": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Conf",
	},
	"config.ru": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "ConfigRu",
	},
	"cp": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Cp",
	},
	"cpp": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Cpp",
	},
	"cppm": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Cppm",
	},
	"cpy": {
		Icon:       "⚙",
		Color:      "#005ca5",
		CtermColor: "25",
		Name:       "Cobol",
	},
	"cr": {
		Icon:       "",
		Color:      "#c8c8c8",
		CtermColor: "251",
		Name:       "Crystal",
	},
	"crdownload": {
		Icon:       "",
		Color:      "#44cda8",
		CtermColor: "43",
		Name:       "Crdownload",
	},
	"cs": {
		Icon:       "󰌛",
		Color:      "#596706",
		CtermColor: "58",
		Name:       "Cs",
	},
	"csh": {
		Icon:       "",
		Color:      "#4d5a5e",
		CtermColor: "240",
		Name:       "Csh",
	},
	"cshtml": {
		Icon:       "󱦗",
		Color:      "#512bd4",
		CtermColor: "56",
		Name:       "RazorPage",
	},
	"cson": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Cson",
	},
	"csproj": {
		Icon:       "󰪮",
		Color:      "#512bd4",
		CtermColor: "56",
		Name:       "CSharpProject",
	},
	"css": {
		Icon:       "",
		Color:      "#42a5f5",
		CtermColor: "75",
		Name:       "Css",
	},
	"csv": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Csv",
	},
	"cts": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Cts",
	},
	"cu": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "cuda",
	},
	"cue": {
		Icon:       "󰲹",
		Color:      "#ed95ae",
		CtermColor: "211",
		Name:       "Cue",
	},
	"cuh": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "cudah",
	},
	"cxx": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Cxx",
	},
	"cxxm": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Cxxm",
	},
	"d": {
		Icon:       "",
		Color:      "#427819",
		CtermColor: "28",
		Name:       "D",
	},
	"d.ts": {
		Icon:       "",
		Color:      "#d59855",
		CtermColor: "172",
		Name:       "TypeScriptDeclaration",
	},
	"dart": {
		Icon:       "",
		Color:      "#03589C",
		CtermColor: "25",
		Name:       "Dart",
	},
	"db": {
		Icon:       "",
		Color:      "#dad8d8",
		CtermColor: "188",
		Name:       "Db",
	},
	"dconf": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "Dconf",
	},
	"desktop": {
		Icon:       "",
		Color:      "#563d7c",
		CtermColor: "54",
		Name:       "DesktopEntry",
	},
	"diff": {
		Icon:       "",
		Color:      "#41535b",
		CtermColor: "239",
		Name:       "Diff",
	},
	"dll": {
		Icon:       "",
		Color:      "#4d2c0b",
		CtermColor: "52",
		Name:       "Dll",
	},
	"doc": {
		Icon:       "󰈬",
		Color:      "#185abd",
		CtermColor: "26",
		Name:       "Doc",
	},
	"Dockerfile": {
		Icon:       "󰡨",
		Color:      "#458ee6",
		CtermColor: "68",
		Name:       "Dockerfile",
	},
	"docx": {
		Icon:       "󰈬",
		Color:      "#185abd",
		CtermColor: "26",
		Name:       "Docx",
	},
	"dot": {
		Icon:       "󱁉",
		Color:      "#30638e",
		CtermColor: "24",
		Name:       "Dot",
	},
	"download": {
		Icon:       "",
		Color:      "#44cda8",
		CtermColor: "43",
		Name:       "Download",
	},
	"drl": {
		Icon:       "",
		Color:      "#ffafaf",
		CtermColor: "217",
		Name:       "Drools",
	},
	"dropbox": {
		Icon:       "",
		Color:      "#0061FE",
		CtermColor: "27",
		Name:       "Dropbox",
	},
	"dump": {
		Icon:       "",
		Color:      "#dad8d8",
		CtermColor: "188",
		Name:       "Dump",
	},
	"dwg": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "AutoCADDwg",
	},
	"dxf": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "AutoCADDxf",
	},
	"ebook": {
		Icon:       "",
		Color:      "#eab16d",
		CtermColor: "215",
		Name:       "Ebook",
	},
	"edn": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Edn",
	},
	"eex": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Eex",
	},
	"ejs": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Ejs",
	},
	"elf": {
		Icon:       "",
		Color:      "#9F0500",
		CtermColor: "124",
		Name:       "Elf",
	},
	"el": {
		Icon:       "",
		Color:      "#8172be",
		CtermColor: "97",
		Name:       "Elisp",
	},
	"elc": {
		Icon:       "",
		Color:      "#8172be",
		CtermColor: "97",
		Name:       "Elisp",
	},
	"elm": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Elm",
	},
	"eln": {
		Icon:       "",
		Color:      "#8172be",
		CtermColor: "97",
		Name:       "Elisp",
	},
	"env": {
		Icon:       "",
		Color:      "#faf743",
		CtermColor: "227",
		Name:       "Env",
	},
	"eot": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "EmbeddedOpenTypeFont",
	},
	"epp": {
		Icon:       "",
		Color:      "#FFA61A",
		CtermColor: "214",
		Name:       "Epp",
	},
	"epub": {
		Icon:       "",
		Color:      "#eab16d",
		CtermColor: "215",
		Name:       "Epub",
	},
	"erb": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "Erb",
	},
	"erl": {
		Icon:       "",
		Color:      "#B83998",
		CtermColor: "163",
		Name:       "Erl",
	},
	"ex": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Ex",
	},
	"exe": {
		Icon:       "",
		Color:      "#9F0500",
		CtermColor: "124",
		Name:       "Exe",
	},
	"exs": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Exs",
	},
	"f#": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Fsharp",
	},
	"f3d": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Fusion360",
	},
	"f90": {
		Icon:       "󱈚",
		Color:      "#734f96",
		CtermColor: "97",
		Name:       "Fortran",
	},
	"fbx": {
		Icon:       "󰆧",
		Color:      "#888888",
		CtermColor: "102",
		Name:       "3DObjectFile",
	},
	"fcbak": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fcmacro": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fcmat": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fcparam": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fcscript": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fcstd": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fcstd1": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fctb": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fctl": {
		Icon:       "",
		Color:      "#cb0d0d",
		CtermColor: "160",
		Name:       "FreeCAD",
	},
	"fdmdownload": {
		Icon:       "",
		Color:      "#44cda8",
		CtermColor: "43",
		Name:       "Fdmdownload",
	},
	"flac": {
		Icon:       "",
		Color:      "#0075aa",
		CtermColor: "24",
		Name:       "FreeLosslessAudioCodec",
	},
	"flc": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "FIGletFontControl",
	},
	"flf": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "FIGletFontFormat",
	},
	"fnl": {
		Icon:       "",
		Color:      "#fff3d7",
		CtermColor: "230",
		Name:       "Fennel",
	},
	"fish": {
		Icon:       "",
		Color:      "#4d5a5e",
		CtermColor: "240",
		Name:       "Fish",
	},
	"fs": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Fs",
	},
	"fsi": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Fsi",
	},
	"fsscript": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Fsscript",
	},
	"fsx": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Fsx",
	},
	"gcode": {
		Icon:       "󰐫",
		Color:      "#1471ad",
		CtermColor: "32",
		Name:       "GCode",
	},
	"gd": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "GDScript",
	},
	"gemspec": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "Gemspec",
	},
	"gif": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Gif",
	},
	"git": {
		Icon:       "",
		Color:      "#F14C28",
		CtermColor: "196",
		Name:       "GitLogo",
	},
	"glb": {
		Icon:       "",
		Color:      "#FFB13B",
		CtermColor: "214",
		Name:       "BinaryGLTF",
	},
	"gnumakefile": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Makefile",
	},
	"go": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Go",
	},
	"godot": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "GodotProject",
	},
	"gql": {
		Icon:       "",
		Color:      "#e535ab",
		CtermColor: "199",
		Name:       "GraphQL",
	},
	"graphql": {
		Icon:       "",
		Color:      "#e535ab",
		CtermColor: "199",
		Name:       "GraphQL",
	},
	"gresource": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "GTK",
	},
	"gv": {
		Icon:       "󱁉",
		Color:      "#30638e",
		CtermColor: "24",
		Name:       "Gv",
	},
	"gz": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Gz",
	},
	"h": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "H",
	},
	"haml": {
		Icon:       "",
		Color:      "#eaeae1",
		CtermColor: "255",
		Name:       "Haml",
	},
	"hx": {
		Icon:       "",
		Color:      "#ea8220",
		CtermColor: "208",
		Name:       "Haxe",
	},
	"hbs": {
		Icon:       "",
		Color:      "#f0772b",
		CtermColor: "202",
		Name:       "Hbs",
	},
	"hex": {
		Icon:       "",
		Color:      "#2e63ff",
		CtermColor: "27",
		Name:       "Hexadecimal",
	},
	"heex": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Heex",
	},
	"hh": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Hh",
	},
	"hpp": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Hpp",
	},
	"hrl": {
		Icon:       "",
		Color:      "#B83998",
		CtermColor: "163",
		Name:       "Hrl",
	},
	"hs": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Hs",
	},
	"htm": {
		Icon:       "",
		Color:      "#e34c26",
		CtermColor: "196",
		Name:       "Htm",
	},
	"html": {
		Icon:       "",
		Color:      "#e44d26",
		CtermColor: "196",
		Name:       "Html",
	},
	"huff": {
		Icon:       "󰡘",
		Color:      "#4242c7",
		CtermColor: "56",
		Name:       "Huff",
	},
	"hurl": {
		Icon:       "",
		Color:      "#ff0288",
		CtermColor: "198",
		Name:       "Hurl",
	},
	"hxx": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Hxx",
	},
	"ixx": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Ixx",
	},
	"ico": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Ico",
	},
	"ical": {
		Icon:       "",
		Color:      "#2B2e83",
		CtermColor: "18",
		Name:       "Ical",
	},
	"icalendar": {
		Icon:       "",
		Color:      "#2B2e83",
		CtermColor: "18",
		Name:       "Icalendar",
	},
	"ics": {
		Icon:       "",
		Color:      "#2B2e83",
		CtermColor: "18",
		Name:       "Ics",
	},
	"ifb": {
		Icon:       "",
		Color:      "#2B2e83",
		CtermColor: "18",
		Name:       "Ifb",
	},
	"ifc": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Ifc",
	},
	"ige": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Ige",
	},
	"iges": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Iges",
	},
	"igs": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Igs",
	},
	"image": {
		Icon:       "",
		Color:      "#d0bec8",
		CtermColor: "181",
		Name:       "Image",
	},
	"img": {
		Icon:       "",
		Color:      "#d0bec8",
		CtermColor: "181",
		Name:       "Img",
	},
	"import": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "ImportConfiguration",
	},
	"info": {
		Icon:       "",
		Color:      "#ffffcd",
		CtermColor: "230",
		Name:       "Info",
	},
	"ini": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Ini",
	},
	"ino": {
		Icon:       "",
		Color:      "#56b6c2",
		CtermColor: "73",
		Name:       "Arduino",
	},
	"iso": {
		Icon:       "",
		Color:      "#d0bec8",
		CtermColor: "181",
		Name:       "Iso",
	},
	"ipynb": {
		Icon:       "",
		Color:      "#51a0cf",
		CtermColor: "74",
		Name:       "Notebook",
	},
	"java": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "Java",
	},
	"jl": {
		Icon:       "",
		Color:      "#a270ba",
		CtermColor: "133",
		Name:       "Jl",
	},
	"jwmrc": {
		Icon:       "",
		Color:      "#0078cd",
		CtermColor: "32",
		Name:       "JWM",
	},
	"jpeg": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Jpeg",
	},
	"jpg": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Jpg",
	},
	"js": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Js",
	},
	"json": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Json",
	},
	"json5": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Json5",
	},
	"jsonc": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "Jsonc",
	},
	"jsx": {
		Icon:       "",
		Color:      "#20c2e3",
		CtermColor: "45",
		Name:       "Jsx",
	},
	"jxl": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "JpegXl",
	},
	"kbx": {
		Icon:       "󰯄",
		Color:      "#737672",
		CtermColor: "243",
		Name:       "Kbx",
	},
	"kdb": {
		Icon:       "",
		Color:      "#529b34",
		CtermColor: "71",
		Name:       "Kdb",
	},
	"kdbx": {
		Icon:       "",
		Color:      "#529b34",
		CtermColor: "71",
		Name:       "Kdbx",
	},
	"kdenlive": {
		Icon:       "",
		Color:      "#83b8f2",
		CtermColor: "110",
		Name:       "Kdenlive",
	},
	"kdenlivetitle": {
		Icon:       "",
		Color:      "#83b8f2",
		CtermColor: "110",
		Name:       "Kdenlive",
	},
	"kicad_dru": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"kicad_mod": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"kicad_pcb": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"kicad_prl": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"kicad_pro": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"kicad_sch": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"kicad_sym": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"kicad_wks": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "KiCad",
	},
	"ko": {
		Icon:       "",
		Color:      "#dcddd6",
		CtermColor: "253",
		Name:       "LinuxKernelObject",
	},
	"kpp": {
		Icon:       "",
		Color:      "#f245fb",
		CtermColor: "201",
		Name:       "Krita",
	},
	"kra": {
		Icon:       "",
		Color:      "#f245fb",
		CtermColor: "201",
		Name:       "Krita",
	},
	"krz": {
		Icon:       "",
		Color:      "#f245fb",
		CtermColor: "201",
		Name:       "Krita",
	},
	"ksh": {
		Icon:       "",
		Color:      "#4d5a5e",
		CtermColor: "240",
		Name:       "Ksh",
	},
	"kt": {
		Icon:       "",
		Color:      "#7F52FF",
		CtermColor: "99",
		Name:       "Kotlin",
	},
	"kts": {
		Icon:       "",
		Color:      "#7F52FF",
		CtermColor: "99",
		Name:       "KotlinScript",
	},
	"lck": {
		Icon:       "",
		Color:      "#bbbbbb",
		CtermColor: "250",
		Name:       "Lock",
	},
	"leex": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Leex",
	},
	"less": {
		Icon:       "",
		Color:      "#563d7c",
		CtermColor: "54",
		Name:       "Less",
	},
	"lff": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "LibrecadFontFile",
	},
	"lhs": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Lhs",
	},
	"lib": {
		Icon:       "",
		Color:      "#4d2c0b",
		CtermColor: "52",
		Name:       "Lib",
	},
	"license": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "License",
	},
	"liquid": {
		Icon:       "",
		Color:      "#95BF47",
		CtermColor: "106",
		Name:       "Liquid",
	},
	"lock": {
		Icon:       "",
		Color:      "#bbbbbb",
		CtermColor: "250",
		Name:       "Lock",
	},
	"log": {
		Icon:       "󰌱",
		Color:      "#dddddd",
		CtermColor: "253",
		Name:       "Log",
	},
	"lrc": {
		Icon:       "󰨖",
		Color:      "#ffb713",
		CtermColor: "214",
		Name:       "Lrc",
	},
	"lua": {
		Icon:       "",
		Color:      "#51a0cf",
		CtermColor: "74",
		Name:       "Lua",
	},
	"luac": {
		Icon:       "",
		Color:      "#51a0cf",
		CtermColor: "74",
		Name:       "Lua",
	},
	"luau": {
		Icon:       "",
		Color:      "#00a2ff",
		CtermColor: "75",
		Name:       "Luau",
	},
	"m3u": {
		Icon:       "󰲹",
		Color:      "#ed95ae",
		CtermColor: "211",
		Name:       "M3u",
	},
	"m3u8": {
		Icon:       "󰲹",
		Color:      "#ed95ae",
		CtermColor: "211",
		Name:       "M3u8",
	},
	"m4a": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "MPEG4",
	},
	"m4v": {
		Icon:       "",
		Color:      "#FD971F",
		CtermColor: "208",
		Name:       "M4V",
	},
	"magnet": {
		Icon:       "",
		Color:      "#a51b16",
		CtermColor: "124",
		Name:       "Magnet",
	},
	"makefile": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Makefile",
	},
	"markdown": {
		Icon:       "",
		Color:      "#dddddd",
		CtermColor: "253",
		Name:       "Markdown",
	},
	"material": {
		Icon:       "󰔉",
		Color:      "#B83998",
		CtermColor: "163",
		Name:       "Material",
	},
	"md": {
		Icon:       "",
		Color:      "#dddddd",
		CtermColor: "253",
		Name:       "Md",
	},
	"md5": {
		Icon:       "󰕥",
		Color:      "#8c86af",
		CtermColor: "103",
		Name:       "Md5",
	},
	"mdx": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Mdx",
	},
	"mint": {
		Icon:       "󰌪",
		Color:      "#87c095",
		CtermColor: "108",
		Name:       "Mint",
	},
	"mjs": {
		Icon:       "",
		Color:      "#f1e05a",
		CtermColor: "185",
		Name:       "Mjs",
	},
	"mk": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Makefile",
	},
	"mkv": {
		Icon:       "",
		Color:      "#FD971F",
		CtermColor: "208",
		Name:       "Mkv",
	},
	"ml": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Ml",
	},
	"mli": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Mli",
	},
	"m": {
		Icon:       "",
		Color:      "#599eff",
		CtermColor: "111",
		Name:       "ObjectiveC",
	},
	"mm": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "ObjectiveCPlusPlus",
	},
	"mo": {
		Icon:       "∞",
		Color:      "#9772FB",
		CtermColor: "135",
		Name:       "Motoko",
	},
	"mobi": {
		Icon:       "",
		Color:      "#eab16d",
		CtermColor: "215",
		Name:       "Mobi",
	},
	"mojo": {
		Icon:       "",
		Color:      "#ff4c1f",
		CtermColor: "196",
		Name:       "Mojo",
	},
	"🔥": {
		Icon:       "",
		Color:      "#ff4c1f",
		CtermColor: "196",
		Name:       "Mojo",
	},
	"mov": {
		Icon:       "",
		Color:      "#FD971F",
		CtermColor: "208",
		Name:       "MOV",
	},
	"mp3": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "MPEGAudioLayerIII",
	},
	"mp4": {
		Icon:       "",
		Color:      "#FD971F",
		CtermColor: "208",
		Name:       "Mp4",
	},
	"mpp": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Mpp",
	},
	"msf": {
		Icon:       "",
		Color:      "#137be1",
		CtermColor: "33",
		Name:       "Thunderbird",
	},
	"mts": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Mts",
	},
	"mustache": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Mustache",
	},
	"nfo": {
		Icon:       "",
		Color:      "#ffffcd",
		CtermColor: "230",
		Name:       "Nfo",
	},
	"nim": {
		Icon:       "",
		Color:      "#f3d400",
		CtermColor: "220",
		Name:       "Nim",
	},
	"nix": {
		Icon:       "",
		Color:      "#7ebae4",
		CtermColor: "110",
		Name:       "Nix",
	},
	"nswag": {
		Icon:       "",
		Color:      "#85ea2d",
		CtermColor: "112",
		Name:       "Nswag",
	},
	"nu": {
		Icon:       ">",
		Color:      "#3aa675",
		CtermColor: "36",
		Name:       "Nushell",
	},
	"o": {
		Icon:       "",
		Color:      "#9F0500",
		CtermColor: "124",
		Name:       "ObjectFile",
	},
	"obj": {
		Icon:       "󰆧",
		Color:      "#888888",
		CtermColor: "102",
		Name:       "3DObjectFile",
	},
	"ogg": {
		Icon:       "",
		Color:      "#0075aa",
		CtermColor: "24",
		Name:       "OggVorbis",
	},
	"opus": {
		Icon:       "",
		Color:      "#0075aa",
		CtermColor: "24",
		Name:       "OpusAudioFile",
	},
	"org": {
		Icon:       "",
		Color:      "#77AA99",
		CtermColor: "73",
		Name:       "OrgMode",
	},
	"otf": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "OpenTypeFont",
	},
	"out": {
		Icon:       "",
		Color:      "#9F0500",
		CtermColor: "124",
		Name:       "Out",
	},
	"part": {
		Icon:       "",
		Color:      "#44cda8",
		CtermColor: "43",
		Name:       "Part",
	},
	"patch": {
		Icon:       "",
		Color:      "#41535b",
		CtermColor: "239",
		Name:       "Patch",
	},
	"pck": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "PackedResource",
	},
	"pcm": {
		Icon:       "",
		Color:      "#0075aa",
		CtermColor: "24",
		Name:       "PulseCodeModulation",
	},
	"pdf": {
		Icon:       "",
		Color:      "#b30b00",
		CtermColor: "124",
		Name:       "Pdf",
	},
	"php": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Php",
	},
	"pl": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Pl",
	},
	"pls": {
		Icon:       "󰲹",
		Color:      "#ed95ae",
		CtermColor: "211",
		Name:       "Pls",
	},
	"ply": {
		Icon:       "󰆧",
		Color:      "#888888",
		CtermColor: "102",
		Name:       "3DObjectFile",
	},
	"pm": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Pm",
	},
	"png": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Png",
	},
	"po": {
		Icon:       "",
		Color:      "#2596be",
		CtermColor: "31",
		Name:       "Localization",
	},
	"pot": {
		Icon:       "",
		Color:      "#2596be",
		CtermColor: "31",
		Name:       "Localization",
	},
	"pp": {
		Icon:       "",
		Color:      "#FFA61A",
		CtermColor: "214",
		Name:       "Pp",
	},
	"ppt": {
		Icon:       "󰈧",
		Color:      "#cb4a32",
		CtermColor: "160",
		Name:       "Ppt",
	},
	"prisma": {
		Icon:       "",
		Color:      "#5a67d8",
		CtermColor: "62",
		Name:       "Prisma",
	},
	"pro": {
		Icon:       "",
		Color:      "#e4b854",
		CtermColor: "179",
		Name:       "Prolog",
	},
	"ps1": {
		Icon:       "󰨊",
		Color:      "#4273ca",
		CtermColor: "68",
		Name:       "PsScriptfile",
	},
	"psd1": {
		Icon:       "󰨊",
		Color:      "#6975c4",
		CtermColor: "68",
		Name:       "PsManifestfile",
	},
	"psm1": {
		Icon:       "󰨊",
		Color:      "#6975c4",
		CtermColor: "68",
		Name:       "PsScriptModulefile",
	},
	"psb": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Psb",
	},
	"psd": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Psd",
	},
	"pub": {
		Icon:       "󰷖",
		Color:      "#e3c58e",
		CtermColor: "222",
		Name:       "Pub",
	},
	"pxd": {
		Icon:       "",
		Color:      "#5aa7e4",
		CtermColor: "39",
		Name:       "Pxd",
	},
	"pxi": {
		Icon:       "",
		Color:      "#5aa7e4",
		CtermColor: "39",
		Name:       "Pxi",
	},
	"py": {
		Icon:       "",
		Color:      "#ffbc03",
		CtermColor: "214",
		Name:       "Py",
	},
	"pyc": {
		Icon:       "",
		Color:      "#ffe291",
		CtermColor: "222",
		Name:       "Pyc",
	},
	"pyd": {
		Icon:       "",
		Color:      "#ffe291",
		CtermColor: "222",
		Name:       "Pyd",
	},
	"pyi": {
		Icon:       "",
		Color:      "#ffbc03",
		CtermColor: "214",
		Name:       "Pyi",
	},
	"pyo": {
		Icon:       "",
		Color:      "#ffe291",
		CtermColor: "222",
		Name:       "Pyo",
	},
	"pyx": {
		Icon:       "",
		Color:      "#5aa7e4",
		CtermColor: "39",
		Name:       "Pyx",
	},
	"qm": {
		Icon:       "",
		Color:      "#2596be",
		CtermColor: "31",
		Name:       "Localization",
	},
	"qml": {
		Icon:       "",
		Color:      "#40cd52",
		CtermColor: "77",
		Name:       "Qt",
	},
	"qrc": {
		Icon:       "",
		Color:      "#40cd52",
		CtermColor: "77",
		Name:       "Qt",
	},
	"qss": {
		Icon:       "",
		Color:      "#40cd52",
		CtermColor: "77",
		Name:       "Qt",
	},
	"query": {
		Icon:       "",
		Color:      "#90a850",
		CtermColor: "107",
		Name:       "Query",
	},
	"r": {
		Icon:       "󰟔",
		Color:      "#2266ba",
		CtermColor: "25",
		Name:       "R",
	},
	"rake": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "Rake",
	},
	"rar": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Rar",
	},
	"razor": {
		Icon:       "󱦘",
		Color:      "#512bd4",
		CtermColor: "56",
		Name:       "RazorPage",
	},
	"rb": {
		Icon:       "",
		Color:      "#701516",
		CtermColor: "52",
		Name:       "Rb",
	},
	"res": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "ReScript",
	},
	"resi": {
		Icon:       "",
		Color:      "#f55385",
		CtermColor: "204",
		Name:       "ReScriptInterface",
	},
	"rlib": {
		Icon:       "",
		Color:      "#dea584",
		CtermColor: "216",
		Name:       "Rlib",
	},
	"rmd": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Rmd",
	},
	"rproj": {
		Icon:       "󰗆",
		Color:      "#358a5b",
		CtermColor: "29",
		Name:       "Rproj",
	},
	"rs": {
		Icon:       "",
		Color:      "#dea584",
		CtermColor: "216",
		Name:       "Rs",
	},
	"rss": {
		Icon:       "",
		Color:      "#FB9D3B",
		CtermColor: "215",
		Name:       "Rss",
	},
	"sass": {
		Icon:       "",
		Color:      "#f55385",
		CtermColor: "204",
		Name:       "Sass",
	},
	"sbt": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "sbt",
	},
	"scad": {
		Icon:       "",
		Color:      "#f9d72c",
		CtermColor: "220",
		Name:       "OpenSCAD",
	},
	"scala": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "Scala",
	},
	"sc": {
		Icon:       "",
		Color:      "#cc3e44",
		CtermColor: "167",
		Name:       "ScalaScript",
	},
	"scm": {
		Icon:       "󰘧",
		Color:      "#eeeeee",
		CtermColor: "255",
		Name:       "Scheme",
	},
	"scss": {
		Icon:       "",
		Color:      "#f55385",
		CtermColor: "204",
		Name:       "Scss",
	},
	"sh": {
		Icon:       "",
		Color:      "#4d5a5e",
		CtermColor: "240",
		Name:       "Sh",
	},
	"sha1": {
		Icon:       "󰕥",
		Color:      "#8c86af",
		CtermColor: "103",
		Name:       "Sha1",
	},
	"sha224": {
		Icon:       "󰕥",
		Color:      "#8c86af",
		CtermColor: "103",
		Name:       "Sha224",
	},
	"sha256": {
		Icon:       "󰕥",
		Color:      "#8c86af",
		CtermColor: "103",
		Name:       "Sha256",
	},
	"sha384": {
		Icon:       "󰕥",
		Color:      "#8c86af",
		CtermColor: "103",
		Name:       "Sha384",
	},
	"sha512": {
		Icon:       "󰕥",
		Color:      "#8c86af",
		CtermColor: "103",
		Name:       "Sha512",
	},
	"sig": {
		Icon:       "λ",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Sig",
	},
	"signature": {
		Icon:       "λ",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Signature",
	},
	"skp": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "SketchUp",
	},
	"sldasm": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "SolidWorksAsm",
	},
	"sldprt": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "SolidWorksPrt",
	},
	"slim": {
		Icon:       "",
		Color:      "#e34c26",
		CtermColor: "196",
		Name:       "Slim",
	},
	"sln": {
		Icon:       "",
		Color:      "#854CC7",
		CtermColor: "98",
		Name:       "Sln",
	},
	"slvs": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "SolveSpace",
	},
	"sml": {
		Icon:       "λ",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Sml",
	},
	"so": {
		Icon:       "",
		Color:      "#dcddd6",
		CtermColor: "253",
		Name:       "SharedObject",
	},
	"sol": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Solidity",
	},
	"spec.js": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "SpecJs",
	},
	"spec.jsx": {
		Icon:       "",
		Color:      "#20c2e3",
		CtermColor: "45",
		Name:       "JavaScriptReactSpec",
	},
	"spec.ts": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "SpecTs",
	},
	"spec.tsx": {
		Icon:       "",
		Color:      "#1354bf",
		CtermColor: "26",
		Name:       "TypeScriptReactSpec",
	},
	"sql": {
		Icon:       "",
		Color:      "#dad8d8",
		CtermColor: "188",
		Name:       "Sql",
	},
	"sqlite": {
		Icon:       "",
		Color:      "#dad8d8",
		CtermColor: "188",
		Name:       "Sql",
	},
	"sqlite3": {
		Icon:       "",
		Color:      "#dad8d8",
		CtermColor: "188",
		Name:       "Sql",
	},
	"srt": {
		Icon:       "󰨖",
		Color:      "#ffb713",
		CtermColor: "214",
		Name:       "Srt",
	},
	"ssa": {
		Icon:       "󰨖",
		Color:      "#ffb713",
		CtermColor: "214",
		Name:       "Ssa",
	},
	"stl": {
		Icon:       "󰆧",
		Color:      "#888888",
		CtermColor: "102",
		Name:       "3DObjectFile",
	},
	"strings": {
		Icon:       "",
		Color:      "#2596be",
		CtermColor: "31",
		Name:       "Localization",
	},
	"ste": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Ste",
	},
	"step": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Step",
	},
	"stp": {
		Icon:       "󰻫",
		Color:      "#839463",
		CtermColor: "101",
		Name:       "Stp",
	},
	"styl": {
		Icon:       "",
		Color:      "#8dc149",
		CtermColor: "113",
		Name:       "Styl",
	},
	"sub": {
		Icon:       "󰨖",
		Color:      "#ffb713",
		CtermColor: "214",
		Name:       "Sub",
	},
	"sublime": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Sublime",
	},
	"suo": {
		Icon:       "",
		Color:      "#854CC7",
		CtermColor: "98",
		Name:       "Suo",
	},
	"sv": {
		Icon:       "󰍛",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "SystemVerilog",
	},
	"svelte": {
		Icon:       "",
		Color:      "#ff3e00",
		CtermColor: "196",
		Name:       "Svelte",
	},
	"svh": {
		Icon:       "󰍛",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "SystemVerilog",
	},
	"svg": {
		Icon:       "󰜡",
		Color:      "#FFB13B",
		CtermColor: "214",
		Name:       "Svg",
	},
	"swift": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Swift",
	},
	"t": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Tor",
	},
	"tbc": {
		Icon:       "󰛓",
		Color:      "#1e5cb3",
		CtermColor: "25",
		Name:       "Tcl",
	},
	"tcl": {
		Icon:       "󰛓",
		Color:      "#1e5cb3",
		CtermColor: "25",
		Name:       "Tcl",
	},
	"templ": {
		Icon:       "",
		Color:      "#dbbd30",
		CtermColor: "178",
		Name:       "Templ",
	},
	"terminal": {
		Icon:       "",
		Color:      "#31B53E",
		CtermColor: "34",
		Name:       "Terminal",
	},
	"test.js": {
		Icon:       "",
		Color:      "#cbcb41",
		CtermColor: "185",
		Name:       "TestJs",
	},
	"test.jsx": {
		Icon:       "",
		Color:      "#20c2e3",
		CtermColor: "45",
		Name:       "JavaScriptReactTest",
	},
	"test.ts": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "TestTs",
	},
	"test.tsx": {
		Icon:       "",
		Color:      "#1354bf",
		CtermColor: "26",
		Name:       "TypeScriptReactTest",
	},
	"tex": {
		Icon:       "",
		Color:      "#3D6117",
		CtermColor: "22",
		Name:       "Tex",
	},
	"tf": {
		Icon:       "",
		Color:      "#5F43E9",
		CtermColor: "93",
		Name:       "Terraform",
	},
	"tfvars": {
		Icon:       "",
		Color:      "#5F43E9",
		CtermColor: "93",
		Name:       "TFVars",
	},
	"tgz": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Tgz",
	},
	"tmux": {
		Icon:       "",
		Color:      "#14ba19",
		CtermColor: "34",
		Name:       "Tmux",
	},
	"toml": {
		Icon:       "",
		Color:      "#9c4221",
		CtermColor: "124",
		Name:       "Toml",
	},
	"torrent": {
		Icon:       "",
		Color:      "#44cda8",
		CtermColor: "43",
		Name:       "Torrent",
	},
	"tres": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "GodotTextResource",
	},
	"ts": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "TypeScript",
	},
	"tscn": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "GodotTextScene",
	},
	"tsconfig": {
		Icon:       "",
		Color:      "#FF8700",
		CtermColor: "208",
		Name:       "TypoScriptConfig",
	},
	"tsx": {
		Icon:       "",
		Color:      "#1354bf",
		CtermColor: "26",
		Name:       "Tsx",
	},
	"ttf": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "TrueTypeFont",
	},
	"twig": {
		Icon:       "",
		Color:      "#8dc149",
		CtermColor: "113",
		Name:       "Twig",
	},
	"txz": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Txz",
	},
	"typoscript": {
		Icon:       "",
		Color:      "#FF8700",
		CtermColor: "208",
		Name:       "TypoScript",
	},
	"txt": {
		Icon:       "󰈙",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Txt",
	},
	"ui": {
		Icon:       "",
		Color:      "#0c306e",
		CtermColor: "17",
		Name:       "UI",
	},
	"v": {
		Icon:       "󰍛",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "Verilog",
	},
	"vala": {
		Icon:       "",
		Color:      "#7239b3",
		CtermColor: "91",
		Name:       "Vala",
	},
	"vh": {
		Icon:       "󰍛",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "Verilog",
	},
	"vhd": {
		Icon:       "󰍛",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "VHDL",
	},
	"vhdl": {
		Icon:       "󰍛",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "VHDL",
	},
	"vim": {
		Icon:       "",
		Color:      "#019833",
		CtermColor: "28",
		Name:       "Vim",
	},
	"vsh": {
		Icon:       "",
		Color:      "#5d87bf",
		CtermColor: "67",
		Name:       "Vlang",
	},
	"vsix": {
		Icon:       "",
		Color:      "#854CC7",
		CtermColor: "98",
		Name:       "Vsix",
	},
	"vue": {
		Icon:       "",
		Color:      "#8dc149",
		CtermColor: "113",
		Name:       "Vue",
	},
	"wasm": {
		Icon:       "",
		Color:      "#5c4cdb",
		CtermColor: "62",
		Name:       "Wasm",
	},
	"wav": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "WaveformAudioFile",
	},
	"webm": {
		Icon:       "",
		Color:      "#FD971F",
		CtermColor: "208",
		Name:       "Webm",
	},
	"webmanifest": {
		Icon:       "",
		Color:      "#f1e05a",
		CtermColor: "185",
		Name:       "Webmanifest",
	},
	"webp": {
		Icon:       "",
		Color:      "#a074c4",
		CtermColor: "140",
		Name:       "Webp",
	},
	"webpack": {
		Icon:       "󰜫",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Webpack",
	},
	"wma": {
		Icon:       "",
		Color:      "#00afff",
		CtermColor: "39",
		Name:       "WindowsMediaAudio",
	},
	"woff": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "WebOpenFontFormat",
	},
	"woff2": {
		Icon:       "",
		Color:      "#ECECEC",
		CtermColor: "255",
		Name:       "WebOpenFontFormat",
	},
	"wrl": {
		Icon:       "󰆧",
		Color:      "#888888",
		CtermColor: "102",
		Name:       "VRML",
	},
	"wrz": {
		Icon:       "󰆧",
		Color:      "#888888",
		CtermColor: "102",
		Name:       "VRML",
	},
	"x": {
		Icon:       "",
		Color:      "#599eff",
		CtermColor: "111",
		Name:       "Logos",
	},
	"xm": {
		Icon:       "",
		Color:      "#519aba",
		CtermColor: "74",
		Name:       "Logos",
	},
	"xaml": {
		Icon:       "󰙳",
		Color:      "#512bd4",
		CtermColor: "56",
		Name:       "Xaml",
	},
	"xcf": {
		Icon:       "",
		Color:      "#635b46",
		CtermColor: "240",
		Name:       "GIMP",
	},
	"xcplayground": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "XcPlayground",
	},
	"xcstrings": {
		Icon:       "",
		Color:      "#2596be",
		CtermColor: "31",
		Name:       "XcLocalization",
	},
	"xls": {
		Icon:       "󰈛",
		Color:      "#207245",
		CtermColor: "29",
		Name:       "Xls",
	},
	"xlsx": {
		Icon:       "󰈛",
		Color:      "#207245",
		CtermColor: "29",
		Name:       "Xlsx",
	},
	"xml": {
		Icon:       "󰗀",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Xml",
	},
	"xpi": {
		Icon:       "",
		Color:      "#ff1b01",
		CtermColor: "196",
		Name:       "Xpi",
	},
	"xul": {
		Icon:       "",
		Color:      "#e37933",
		CtermColor: "166",
		Name:       "Xul",
	},
	"xz": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Xz",
	},
	"yaml": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Yaml",
	},
	"yml": {
		Icon:       "",
		Color:      "#6d8086",
		CtermColor: "66",
		Name:       "Yml",
	},
	"zig": {
		Icon:       "",
		Color:      "#f69a1b",
		CtermColor: "172",
		Name:       "Zig",
	},
	"zip": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Zip",
	},
	"zsh": {
		Icon:       "",
		Color:      "#89e051",
		CtermColor: "113",
		Name:       "Zsh",
	},
	"zst": {
		Icon:       "",
		Color:      "#eca517",
		CtermColor: "214",
		Name:       "Zst",
	},
}

var iconsByFileOS = map[string]IconDetails{
	"apple": {
		Icon:       "",
		Color:      "#A2AAAD",
		CtermColor: "248",
		Name:       "Apple",
	},
	"windows": {
		Icon:       "",
		Color:      "#00A4EF",
		CtermColor: "39",
		Name:       "Windows",
	},
	"linux": {
		Icon:       "",
		Color:      "#fdfdfb",
		CtermColor: "231",
		Name:       "Linux",
	},
	"alma": {
		Icon:       "",
		Color:      "#ff4649",
		CtermColor: "203",
		Name:       "Almalinux",
	},
	"alpine": {
		Icon:       "",
		Color:      "#0d597f",
		CtermColor: "24",
		Name:       "Alpine",
	},
	"aosc": {
		Icon:       "",
		Color:      "#c00000",
		CtermColor: "124",
		Name:       "AOSC",
	},
	"arch": {
		Icon:       "󰣇",
		Color:      "#0f94d2",
		CtermColor: "67",
		Name:       "Arch",
	},
	"archcraft": {
		Icon:       "",
		Color:      "#86bba3",
		CtermColor: "108",
		Name:       "Archcraft",
	},
	"archlabs": {
		Icon:       "",
		Color:      "#503f42",
		CtermColor: "238",
		Name:       "Archlabs",
	},
	"arcolinux": {
		Icon:       "",
		Color:      "#6690eb",
		CtermColor: "68",
		Name:       "ArcoLinux",
	},
	"artix": {
		Icon:       "",
		Color:      "#41b4d7",
		CtermColor: "38",
		Name:       "Artix",
	},
	"biglinux": {
		Icon:       "",
		Color:      "#189fc8",
		CtermColor: "38",
		Name:       "BigLinux",
	},
	"centos": {
		Icon:       "",
		Color:      "#a2518d",
		CtermColor: "132",
		Name:       "Centos",
	},
	"crystallinux": {
		Icon:       "",
		Color:      "#a900ff",
		CtermColor: "129",
		Name:       "CrystalLinux",
	},
	"debian": {
		Icon:       "",
		Color:      "#a80030",
		CtermColor: "88",
		Name:       "Debian",
	},
	"deepin": {
		Icon:       "",
		Color:      "#2ca7f8",
		CtermColor: "39",
		Name:       "Deepin",
	},
	"devuan": {
		Icon:       "",
		Color:      "#404a52",
		CtermColor: "238",
		Name:       "Devuan",
	},
	"elementary": {
		Icon:       "",
		Color:      "#5890c2",
		CtermColor: "67",
		Name:       "Elementary",
	},
	"endeavour": {
		Icon:       "",
		Color:      "#7b3db9",
		CtermColor: "91",
		Name:       "Endeavour",
	},
	"fedora": {
		Icon:       "",
		Color:      "#072a5e",
		CtermColor: "17",
		Name:       "Fedora",
	},
	"freebsd": {
		Icon:       "",
		Color:      "#c90f02",
		CtermColor: "160",
		Name:       "FreeBSD",
	},
	"garuda": {
		Icon:       "",
		Color:      "#2974e1",
		CtermColor: "33",
		Name:       "GarudaLinux",
	},
	"gentoo": {
		Icon:       "󰣨",
		Color:      "#b1abce",
		CtermColor: "146",
		Name:       "Gentoo",
	},
	"guix": {
		Icon:       "",
		Color:      "#ffcc00",
		CtermColor: "220",
		Name:       "Guix",
	},
	"hyperbola": {
		Icon:       "",
		Color:      "#c0c0c0",
		CtermColor: "250",
		Name:       "HyperbolaGNULinuxLibre",
	},
	"illumos": {
		Icon:       "",
		Color:      "#ff430f",
		CtermColor: "196",
		Name:       "Illumos",
	},
	"kali": {
		Icon:       "",
		Color:      "#2777ff",
		CtermColor: "69",
		Name:       "Kali",
	},
	"kdeneon": {
		Icon:       "",
		Color:      "#20a6a4",
		CtermColor: "37",
		Name:       "KDEneon",
	},
	"kubuntu": {
		Icon:       "",
		Color:      "#007ac2",
		CtermColor: "32",
		Name:       "Kubuntu",
	},
	"locos": {
		Icon:       "",
		Color:      "#fab402",
		CtermColor: "214",
		Name:       "LocOS",
	},
	"lxle": {
		Icon:       "",
		Color:      "#474747",
		CtermColor: "238",
		Name:       "LXLE",
	},
	"mageia": {
		Icon:       "",
		Color:      "#2397d4",
		CtermColor: "67",
		Name:       "Mageia",
	},
	"manjaro": {
		Icon:       "",
		Color:      "#33b959",
		CtermColor: "35",
		Name:       "Manjaro",
	},
	"mint": {
		Icon:       "󰣭",
		Color:      "#66af3d",
		CtermColor: "70",
		Name:       "Mint",
	},
	"mxlinux": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "MXLinux",
	},
	"nixos": {
		Icon:       "",
		Color:      "#7ab1db",
		CtermColor: "110",
		Name:       "NixOS",
	},
	"openbsd": {
		Icon:       "",
		Color:      "#f2ca30",
		CtermColor: "220",
		Name:       "OpenBSD",
	},
	"opensuse": {
		Icon:       "",
		Color:      "#6fb424",
		CtermColor: "70",
		Name:       "openSUSE",
	},
	"parabola": {
		Icon:       "",
		Color:      "#797dac",
		CtermColor: "103",
		Name:       "ParabolaGNULinuxLibre",
	},
	"parrot": {
		Icon:       "",
		Color:      "#54deff",
		CtermColor: "45",
		Name:       "Parrot",
	},
	"pop_os": {
		Icon:       "",
		Color:      "#48b9c7",
		CtermColor: "73",
		Name:       "Pop_OS",
	},
	"postmarketos": {
		Icon:       "",
		Color:      "#009900",
		CtermColor: "28",
		Name:       "postmarketOS",
	},
	"puppylinux": {
		Icon:       "",
		Color:      "#a2aeb9",
		CtermColor: "145",
		Name:       "PuppyLinux",
	},
	"qubesos": {
		Icon:       "",
		Color:      "#3774d8",
		CtermColor: "33",
		Name:       "QubesOS",
	},
	"raspberry_pi": {
		Icon:       "",
		Color:      "#be1848",
		CtermColor: "161",
		Name:       "RaspberryPiOS",
	},
	"redhat": {
		Icon:       "󱄛",
		Color:      "#EE0000",
		CtermColor: "196",
		Name:       "Redhat",
	},
	"rocky": {
		Icon:       "",
		Color:      "#0fb37d",
		CtermColor: "36",
		Name:       "RockyLinux",
	},
	"sabayon": {
		Icon:       "",
		Color:      "#c6c6c6",
		CtermColor: "251",
		Name:       "Sabayon",
	},
	"slackware": {
		Icon:       "",
		Color:      "#475fa9",
		CtermColor: "61",
		Name:       "Slackware",
	},
	"solus": {
		Icon:       "",
		Color:      "#4b5163",
		CtermColor: "239",
		Name:       "Solus",
	},
	"tails": {
		Icon:       "",
		Color:      "#56347c",
		CtermColor: "54",
		Name:       "Tails",
	},
	"trisquel": {
		Icon:       "",
		Color:      "#0f58b6",
		CtermColor: "25",
		Name:       "TrisquelGNULinux",
	},
	"ubuntu": {
		Icon:       "",
		Color:      "#dd4814",
		CtermColor: "196",
		Name:       "Ubuntu",
	},
	"vanillaos": {
		Icon:       "",
		Color:      "#fabd4d",
		CtermColor: "214",
		Name:       "VanillaOS",
	},
	"void": {
		Icon:       "",
		Color:      "#295340",
		CtermColor: "23",
		Name:       "Void",
	},
	"xerolinux": {
		Icon:       "",
		Color:      "#888fe2",
		CtermColor: "104",
		Name:       "XeroLinux",
	},
	"zorin": {
		Icon:       "",
		Color:      "#14a1e8",
		CtermColor: "39",
		Name:       "Zorin",
	},
}

var iconsByDesktopEnvironment = map[string]IconDetails{
	"budgie": {
		Icon:       "",
		Color:      "#4e5361",
		CtermColor: "240",
		Name:       "Budgie",
	},
	"cinnamon": {
		Icon:       "",
		Color:      "#dc682e",
		CtermColor: "166",
		Name:       "Cinnamon",
	},
	"gnome": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "GNOME",
	},
	"lxde": {
		Icon:       "",
		Color:      "#a4a4a4",
		CtermColor: "248",
		Name:       "LXDE",
	},
	"lxqt": {
		Icon:       "",
		Color:      "#0191d2",
		CtermColor: "32",
		Name:       "LXQt",
	},
	"mate": {
		Icon:       "",
		Color:      "#9bda5c",
		CtermColor: "113",
		Name:       "MATE",
	},
	"plasma": {
		Icon:       "",
		Color:      "#1b89f4",
		CtermColor: "33",
		Name:       "KDEPlasma",
	},
	"xfce": {
		Icon:       "",
		Color:      "#00aadf",
		CtermColor: "74",
		Name:       "Xfce",
	},
}

var iconsByWindowManager = map[string]IconDetails{
	"awesomewm": {
		Icon:       "",
		Color:      "#535d6c",
		CtermColor: "59",
		Name:       "awesome",
	},
	"bspwm": {
		Icon:       "",
		Color:      "#4f4f4f",
		CtermColor: "239",
		Name:       "BSPWM",
	},
	"dwm": {
		Icon:       "",
		Color:      "#1177aa",
		CtermColor: "31",
		Name:       "dwm",
	},
	"enlightenment": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "Enlightenment",
	},
	"fluxbox": {
		Icon:       "",
		Color:      "#555555",
		CtermColor: "240",
		Name:       "Fluxbox",
	},
	"hyprland": {
		Icon:       "",
		Color:      "#00aaae",
		CtermColor: "37",
		Name:       "Hyprland",
	},
	"i3": {
		Icon:       "",
		Color:      "#e8ebee",
		CtermColor: "255",
		Name:       "i3",
	},
	"jwm": {
		Icon:       "",
		Color:      "#0078cd",
		CtermColor: "32",
		Name:       "JWM",
	},
	"qtile": {
		Icon:       "",
		Color:      "#ffffff",
		CtermColor: "231",
		Name:       "Qtile",
	},
	"sway": {
		Icon:       "",
		Color:      "#68751c",
		CtermColor: "64",
		Name:       "Sway",
	},
	"xmonad": {
		Icon:       "",
		Color:      "#fd4d5d",
		CtermColor: "203",
		Name:       "xmonad",
	},
}

var ignoreNamesList = []string{
	"PackageJson",
	"PackageLockJson",
	"TSConfig",
	"Json",
	"Json5",
	"Default",
	"NPMrc",
	"GitIgnore",
	"Svg",
	"Png",
	"Jpg",
	"Favicon",
	// "Md",
	"Log",
	"Lock",
}
